### ISSUE TITLE
No Git tag associated with released versions

### ISSUE THREAD

**Issue by amarshall** [bitwarden/sdk-internal#12]
Hi, this repo has associated versions in the [NPM registry](https://www.npmjs.com/package/@bitwarden/sdk-internal), but none here (and the `package.json` file has `0.0.0`). This makes determining the source code associated with a registry release more difficult than it perhaps should be (though it can potentially be gleaned from the [release workflow](https://github.com/bitwarden/sdk-internal/actions/workflows/publish-internal.yml), this is not as trivial as just referencing a Git tag.

**Comment by Hinton** [comment]
Hi @amarshall,

We partially solved this with https://github.com/bitwarden/sdk-internal/pull/17 which includes the build id in the version number. This should allow easy mapping by getting the appropriate run in https://github.com/bitwarden/sdk-internal/actions/workflows/publish-wasm-internal.yml and checking the git hash. Is this satisfactory?

**Comment by amarshall** [comment]
GitHub Actions logs are only retained for up to 90 days (see [docs](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization)), so it only works for a limited period of time.

**Comment by brjsp** [comment]
@amarshall Thanks for alerting me to this. I've manually archived the existing versions at https://github.com/brjsp/sdk-internal/tags

(I'm not affiliated with Bitwarden but i maintain the <a href="https://build.opensuse.org/package/show/devel:languages:nodejs/bitwarden">package in openSUSE</a>.)

**Comment by Hinton** [comment]
Hmm, would including a `VERSION` file on npm, containing the git hash work?
